# Generated by Django 5.0.4 on 2024-04-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.TextField()),
                ('wireless', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('type', models.TextField()),
                ('capability', models.TextField()),
                ('connectivity', models.TextField()),
                ('impact', models.FloatField(blank=True, null=True)),
                ('risk', models.FloatField(blank=True, null=True)),
                ('sustainability', models.FloatField(blank=True, null=True)),
                ('app', models.TextField(null=True)),
                ('power', models.TextField(null=True)),
                ('energy', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('n_app', models.IntegerField()),
                ('impact', models.FloatField(blank=True, null=True)),
                ('risk', models.FloatField(blank=True, null=True)),
                ('sustainability', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('description', models.TextField()),
                ('baseSeverity', models.TextField()),
                ('baseScore', models.FloatField()),
                ('impactScore', models.FloatField()),
                ('exploitabilityScore', models.FloatField()),
                ('vector', models.TextField()),
                ('cwe', models.TextField()),
                ('version', models.FloatField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectionvulnerabilities', to='albacsp_app.connection')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='first_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstdevice', to='albacsp_app.device'),
        ),
        migrations.AddField(
            model_name='connection',
            name='second_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seconddevice', to='albacsp_app.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='albacsp_app.home'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('description', models.TextField()),
                ('baseSeverity', models.TextField()),
                ('baseScore', models.FloatField()),
                ('impactScore', models.FloatField()),
                ('exploitabilityScore', models.FloatField()),
                ('vector', models.TextField()),
                ('cwe', models.TextField()),
                ('version', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='albacsp_app.device')),
            ],
        ),
    ]
