# Generated by Django 5.0.4 on 2024-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True)),
                ('rechargable', models.BooleanField(default=False)),
                ('renewable_source', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='connectionvulnerability',
            name='cwe',
        ),
        migrations.RemoveField(
            model_name='device',
            name='app',
        ),
        migrations.RemoveField(
            model_name='device',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='device',
            name='power',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cwe',
        ),
        migrations.AddField(
            model_name='device',
            name='app_cap',
            field=models.ManyToManyField(blank=True, to='albacsp_app.app'),
        ),
        migrations.AddField(
            model_name='device',
            name='connectivity_cap',
            field=models.ManyToManyField(blank=True, to='albacsp_app.connectivity'),
        ),
        migrations.AddField(
            model_name='connectionvulnerability',
            name='cwe_cap',
            field=models.ManyToManyField(blank=True, to='albacsp_app.cwe'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwe_cap',
            field=models.ManyToManyField(blank=True, to='albacsp_app.cwe'),
        ),
        migrations.AddField(
            model_name='device',
            name='power_supply',
            field=models.ManyToManyField(blank=True, to='albacsp_app.power'),
        ),
    ]
