# Generated by Django 5.0.4 on 2024-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0002_app_connectivity_cwe_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='n_app',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
