# Generated by Django 5.0.4 on 2024-04-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0003_alter_home_n_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cwe',
            old_name='identifier',
            new_name='cwe',
        ),
    ]
