# Generated by Django 5.0.4 on 2024-04-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0006_rename_cwe_cap_vulnerability_cwes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='app_cap',
            new_name='apps',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='connectivity_cap',
            new_name='connectivities',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='power_supply',
            new_name='power_supplies',
        ),
    ]
