# Generated by Django 4.1.3 on 2024-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0008_remove_connection_wireless_connectivity_wireless'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='renewable_source',
            new_name='renewable',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='type',
            new_name='source',
        ),
        migrations.AddField(
            model_name='power',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
    ]
