# Generated by Django 4.2.14 on 2024-09-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0010_alter_device_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='albacsp_app.home'),
        ),
    ]
