# Generated by Django 5.1.7 on 2025-03-27 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0011_alter_device_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='updateFreq',
            field=models.BigIntegerField(default=3600),
        ),
    ]
