# Generated by Django 5.1.7 on 2025-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0012_device_lastupdate_device_updatefreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='updateFreq',
            field=models.BigIntegerField(default=86400),
        ),
    ]
