# Generated by Django 5.1.7 on 2025-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0013_alter_device_updatefreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='risk',
        ),
    ]
