# Generated by Django 5.1.7 on 2025-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albacsp_app', '0014_remove_device_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.TextField(blank=True, null=True),
        ),
    ]
